name: Demo Accounts - Monday

on: [push]
  #schedule:
    #- cron: '0 6 * * 1'

jobs:

# -----------------------------------------------------------------------------------

  Loan-Officer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        #with:
          #build: npm i -D cypress

      - name: Demo Loan Officer
        uses: cypress-io/github-action@v4 # use the explicit version number
        with:
          spec: cypress/e2e/01_Loan_officer.cy.js
          record: true

      # Action Failed
      - name: Send Fail Email
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          # mail server settings
          server_address: smtp.gmail.com
          server_port: 465
          # user credentials
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          # email subject
          subject: Demo Account (${{ github.job }}) is currently unavailable
          # email body as text
          body: |
            The Demo account - ${{ github.job }} - is currently unavailable.
            We will notify you when it is available.
            Thank you for your patience.
          # comma-separated string, send email to
          to: zecbrown1@gmail.com
          # from email name
          from: Nano Status

# -----------------------------------------------------------------------------------

  Loan-Officer-Assistant:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        #with:
          #build: npm i -D cypress


      - name: Demo Loan Officer Assistant
        uses: cypress-io/github-action@v4 # use the explicit version number
        with:
          spec: cypress/e2e/02_Loan_officer_assistant.cy.js

      # Action Failed
      - name: Send Fail Email
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          # mail server settings
          server_address: smtp.gmail.com
          server_port: 465
          # user credentials
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          # email subject
          subject: Demo Account (${{ github.job }}) is currently unavailable
          # email body as text
          body: |
            The Demo account - ${{ github.job }} - is currently unavailable.
            We will notify you when it is available.
            Thank you for your patience.
          # comma-separated string, send email to
          to: zecbrown1@gmail.com
          # from email name
          from: Nano Status

# -----------------------------------------------------------------------------------

  Processor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        #with:
          #build: npm i -D cypress


      - name: Demo Processor
        uses: cypress-io/github-action@v4 # use the explicit version number
        with:
          spec: cypress/e2e/03_Processor.cy.js

      # Action Failed
      - name: Send Fail Email
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          # mail server settings
          server_address: smtp.gmail.com
          server_port: 465
          # user credentials
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          # email subject
          subject: Demo Account (${{ github.job }}) is currently unavailable
          # email body as text
          body: |
            The Demo account - ${{ github.job }} - is currently unavailable.
            We will notify you when it is available.
            Thank you for your patience.
          # comma-separated string, send email to
          to: zecbrown1@gmail.com
          # from email name
          from: Nano Status

# -----------------------------------------------------------------------------------

  Specialist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        #with:
          #build: npm i -D cypress


      - name: Demo Specialist
        uses: cypress-io/github-action@v4 # use the explicit version number
        with:
          spec: cypress/e2e/04_Specialist.cy.js

      # Action Failed
      - name: Send Fail Email
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          # mail server settings
          server_address: smtp.gmail.com
          server_port: 465
          # user credentials
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          # email subject
          subject: Demo Account (${{ github.job }}) is currently unavailable
          # email body as text
          body: |
            The Demo account - ${{ github.job }} - is currently unavailable.
            We will notify you when it is available.
            Thank you for your patience.
          # comma-separated string, send email to
          to: zecbrown1@gmail.com
          # from email name
          from: Nano Status

# -----------------------------------------------------------------------------------

  Underwriter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        #with:
          #build: npm i -D cypress


      - name: Demo Underwriter
        uses: cypress-io/github-action@v4 # use the explicit version number
        with:
          spec: cypress/e2e/05_Underwriter.cy.js

      # Action Failed
      - name: Send Fail Email
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          # mail server settings
          server_address: smtp.gmail.com
          server_port: 465
          # user credentials
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          # email subject
          subject: Demo Account (${{ github.job }}) is currently unavailable
          # email body as text
          body: |
            The Demo account - ${{ github.job }} - is currently unavailable.
            We will notify you when it is available.
            Thank you for your patience.
          # comma-separated string, send email to
          to: zecbrown1@gmail.com
          # from email name
          from: Nano Status

# -----------------------------------------------------------------------------------

  Closer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        #with:
          #build: npm i -D cypress


      - name: Demo Closer
        uses: cypress-io/github-action@v4 # use the explicit version number
        with:
          spec: cypress/e2e/06_Closer.cy.js

      # Action Failed
      - name: Send Fail Email
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          # mail server settings
          server_address: smtp.gmail.com
          server_port: 465
          # user credentials
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          # email subject
          subject: Demo Account (${{ github.job }}) is currently unavailable
          # email body as text
          body: |
            The Demo account - ${{ github.job }} - is currently unavailable.
            We will notify you when it is available.
            Thank you for your patience.
          # comma-separated string, send email to
          to: zecbrown1@gmail.com
          # from email name
          from: Nano Status

# -----------------------------------------------------------------------------------

  Funder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        #with:
          #build: npm i -D cypress


      - name: Demo Funder
        uses: cypress-io/github-action@v4 # use the explicit version number
        with:
          spec: cypress/e2e/07_Funder.cy.js

      # Action Failed
      - name: Send Fail Email
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          # mail server settings
          server_address: smtp.gmail.com
          server_port: 465
          # user credentials
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          # email subject
          subject: Demo Account (${{ github.job }}) is currently unavailable
          # email body as text
          body: |
            The Demo account - ${{ github.job }} - is currently unavailable.
            We will notify you when it is available.
            Thank you for your patience.
          # comma-separated string, send email to
          to: zecbrown1@gmail.com
          # from email name
          from: Nano Status

# -----------------------------------------------------------------------------------

  Post-Closer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        #with:
          #build: npm i -D cypress


      - name: Demo Post-Closer
        uses: cypress-io/github-action@v4 # use the explicit version number
        with:
          spec: cypress/e2e/08_Post_Closer.cy.js

      # Action Failed
      - name: Send Fail Email
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          # mail server settings
          server_address: smtp.gmail.com
          server_port: 465
          # user credentials
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          # email subject
          subject: Demo Account (${{ github.job }}) is currently unavailable
          # email body as text
          body: |
            The Demo account - ${{ github.job }} - is currently unavailable.
            We will notify you when it is available.
            Thank you for your patience.
          # comma-separated string, send email to
          to: zecbrown1@gmail.com
          # from email name
          from: Nano Status

# -----------------------------------------------------------------------------------

  # Action was successful
  Success-Email:
    runs-on: ubuntu-latest
    needs: [Loan-Officer,Loan-Officer-Assistant,Processor,Specialist,Underwriter,Closer,Funder,Post-Closer]
    steps:
      - name: Send Success Email
        if: success()
        uses: dawidd6/action-send-mail@v3
        with:
          # mail server settings
          server_address: smtp.gmail.com
          server_port: 465
          # user credentials
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          # email subject
          subject: Demo Training Accounts
          # email body as text
          body: The Demo training accounts are all currently working as expected.
          # comma-separated string, send email to
          to: zecbrown1@gmail.com
          # from email name
          from: Nano Status

# -----------------------------------------------------------------------------------

