name: Cypress Tests

on:
  schedule:
    - cron: '0 * * * *'

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          build: npm i -D cypress
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v4 # use the explicit version number
        with:
          build: npx cypress run --record --key b44d18cc-21e5-45ae-8acb-88b350ec5a27