name: Demo Account Sign In Test

on: [push]
  #schedule:
    #- cron: '0 * * * *'

jobs:
  Loan-Officer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          build: npm i -D cypress
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Demo Loan Officer
        uses: cypress-io/github-action@v4 # use the explicit version number
        with:
          spec: cypress/e2e/01_Loan_officer.cy.js


      - name: Send Email
        uses: dawidd6/action-send-mail@v3
        with:
          # mail server settings
          server_address: smtp.gmail.com
          server_port: 465
          # user credentials
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          # email subject
          subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
          # email body as text
          body: ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
          # comma-separated string, send email to
          to: test-37729@nanolos.com,zecbrown1@gmail.com
          # from email name
          from: John Doe

# -----------------------------------------------------------------------------------

  Loan-Officer-Assistant:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          build: npm i -D cypress
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Demo Loan Officer Assistant
        uses: cypress-io/github-action@v4 # use the explicit version number
        with:
          spec: cypress/e2e/02_Loan_officer_assistant.cy.js

# -----------------------------------------------------------------------------------

  Processor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          build: npm i -D cypress
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Demo Processor
        uses: cypress-io/github-action@v4 # use the explicit version number
        with:
          spec: cypress/e2e/03_Processor.cy.js

# -----------------------------------------------------------------------------------

  Specialist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          build: npm i -D cypress
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Demo Specialist
        uses: cypress-io/github-action@v4 # use the explicit version number
        with:
          spec: cypress/e2e/04_Specialist.cy.js

# -----------------------------------------------------------------------------------

  Underwriter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          build: npm i -D cypress
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Demo Underwriter
        uses: cypress-io/github-action@v4 # use the explicit version number
        with:
          spec: cypress/e2e/05_Underwriter.cy.js

# -----------------------------------------------------------------------------------

  Closer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          build: npm i -D cypress
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Demo Closer
        uses: cypress-io/github-action@v4 # use the explicit version number
        with:
          spec: cypress/e2e/06_Closer.cy.js

# -----------------------------------------------------------------------------------

  Funder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          build: npm i -D cypress
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Demo Funder
        uses: cypress-io/github-action@v4 # use the explicit version number
        with:
          spec: cypress/e2e/07_Funder.cy.js

# -----------------------------------------------------------------------------------

  Post-Closer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          build: npm i -D cypress
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Demo Post-Closer
        uses: cypress-io/github-action@v4 # use the explicit version number
        with:
          spec: cypress/e2e/08_Post_Closer.cy.js

# -----------------------------------------------------------------------------------