name: Demo Account Sign In Test

on: [push]
  #schedule:
    #- cron: '0 * * * *'

jobs:
  Loan-Officer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          build: npm i -D cypress
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Demo Loan Officer
        uses: cypress-io/github-action@v4 # use the explicit version number
        with:
          spec: cypress/e2e/01_Loan_officer.cy.js

      - name: Test Success
          uses: rjstone/discord-webhook-notify@v1
          if: success()
          with:
              severity: info
              details: Test Succeeded!
              webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Test Failure
          uses: rjstone/discord-webhook-notify@v1
          if: failure()
          with:
              severity: error
              details: Test Failed!
              webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Test Cancelled
          uses: rjstone/discord-webhook-notify@v1
          if: cancelled()
          with:
              severity: warn
              details: Test Cancelled!
              webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}


# -----------------------------------------------------------------------------------

  Loan-Officer-Assistant:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          build: npm i -D cypress
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Demo Loan Officer Assistant
        uses: cypress-io/github-action@v4 # use the explicit version number
        with:
          spec: cypress/e2e/02_Loan_officer_assistant.cy.js

# -----------------------------------------------------------------------------------

  Processor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          build: npm i -D cypress
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Demo Processor
        uses: cypress-io/github-action@v4 # use the explicit version number
        with:
          spec: cypress/e2e/03_Processor.cy.js

# -----------------------------------------------------------------------------------

  Specialist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          build: npm i -D cypress
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Demo Specialist
        uses: cypress-io/github-action@v4 # use the explicit version number
        with:
          spec: cypress/e2e/04_Specialist.cy.js

# -----------------------------------------------------------------------------------

  Underwriter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          build: npm i -D cypress
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Demo Underwriter
        uses: cypress-io/github-action@v4 # use the explicit version number
        with:
          spec: cypress/e2e/05_Underwriter.cy.js

# -----------------------------------------------------------------------------------

  Closer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          build: npm i -D cypress
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Demo Closer
        uses: cypress-io/github-action@v4 # use the explicit version number
        with:
          spec: cypress/e2e/06_Closer.cy.js

# -----------------------------------------------------------------------------------

  Funder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          build: npm i -D cypress
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Demo Funder
        uses: cypress-io/github-action@v4 # use the explicit version number
        with:
          spec: cypress/e2e/07_Funder.cy.js

# -----------------------------------------------------------------------------------

  Post-Closer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          build: npm i -D cypress
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Demo Post-Closer
        uses: cypress-io/github-action@v4 # use the explicit version number
        with:
          spec: cypress/e2e/08_Post_Closer.cy.js

# -----------------------------------------------------------------------------------