name: Demo Account Sign In Test

on: [push]
  #schedule:
    #- cron: '0 * * * *'

jobs:
  Loan-Officer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          build: npm i -D cypress
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Demo Loan Officer
        uses: cypress-io/github-action@v4 # use the explicit version number
        with:
          build: cypress run --record --key b44d18cc-21e5-45ae-8acb-88b350ec5a27 --parallel